upgrading to python 3.12
djangopackages/djangopackages pull request #1291
Opened 2024-10-15 11:35 UTC by hriprsd

- upgrading to python 3.12
- solves #1285 
- python 3.12 used across project in the notified areas as in the issue. 
- updated changelog as well.

2024-10-15 12:45 UTC, hriprsd commented
Also, could you please add `hacktoberfest-accepted` label to my PR please? would be a huge help! Thanks in advance!

2024-10-16 04:41 UTC, hriprsd commented
Please do let me know if I have missed something/ any more changes are needed. Thanks in advance! 😄

2024-10-16 15:40 UTC, hriprsd commented
Hi. Hoping this will be counted towards my hacktober contribution. P.s would need the label `hacktoberfest-accepted` added to my PR or `hacktober` topic to the repo please. 

Aplogies for the follow ups, but within October would be great
 🙂 

Thanks in advance!

2024-10-16 15:50 UTC, jefftriplett commented
Thank you for your contribution. We'll review this week and add the tag after we accept it. Juggling day jobs but we will not forget to add it :)

2024-10-20 07:41 UTC, saadmk11 requested changes
Awesome work here 💯  This is looking great. 👍 

Seems like some tests are failing because python 3.12 removed `distutils` (`ModuleNotFoundError: No module named 'distutils'`), I think we can fix this by replacing `distutils` with the `packaging` package which we already install.

We may also want to re-compile the `requirements.txt` file with the new python version.
https://github.com/djangopackages/djangopackages/blob/c5fa68de85aa0c7e055ac4eac6090cf5f37d36ad/requirements.txt#L2

2024-10-20 07:41 UTC, saadmk11 commented on pyproject.toml
> -target-version = "py311"
please update the comment above this line (`# Assume Python 3.11`)

2024-10-22 14:05 UTC, hriprsd commented
> Awesome work here 💯 This is looking great. 👍
> 
> Seems like some tests are failing because python 3.12 removed `distutils` (`ModuleNotFoundError: No module named 'distutils'`), I think we can fix this by replacing `distutils` with the `packaging` package which we already install.
> 
> We may also want to re-compile the `requirements.txt` file with the new python version.
> 
> https://github.com/djangopackages/djangopackages/blob/c5fa68de85aa0c7e055ac4eac6090cf5f37d36ad/requirements.txt#L2

Fixed. 😄

2024-10-25 20:43 UTC, merged

2024-10-25 20:46 UTC, jefftriplett commented
TIL this, merged the PR for who only knows what reasons... 

```
$ git push origin hriprsd/main:main
```

2024-10-25 20:50 UTC, jefftriplett commented
@hriprsd thank you for the contribution

@saadmk11 @ryancheley This is fixed in the main, and I found a package that replaces our usage of LooseVersion.